### ISSUE TITLE
MacOS theme preferred font-size

### ISSUE THREAD

**Issue by datafunk** [Ranchero-Software/NetNewsWire#3537]
I was looking for a more appropriate place to post this as AFAIK it's not a bug. All v6.1 themes shipped respond correctly to font-sizes set in preferences, however I cannot for the life of me figure out why my local template isn't picking up the preference setting.

My article markup:
```html
<article>
	<div id="bodyContainer" class="articleBody [[text_size_class]]">[[body]]</div>
</article>
```

I also added (and tried without setting any, just in case) the following CSS, sniffed from [here](https://github.com/Ranchero-Software/NetNewsWire/blob/main/Shared/Article%20Rendering/ArticleTextSize.swift)
```css
.small { font-size: 11px; }
.medium { font-size: 14px; }
.large { font-size: 16px; }
.xlarge { font-size: 18px; }
.xxlarge { font-size: 22px; }
```
to no effect.

I've trawled the docos, but found no particular info. I guess it's a pretty important a11y feature I shouldn't break.
Probably the least of your problems, but I'd be grateful for any hint.
